# -*- coding: utf-8 -*-
"""PeopleBank_AO_2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aINrOY5CtnyHl7V5WsVWsxPBJTicY5mc

### ANÁLISE EXPLORATÓRIA DE DADOS SOBRE 22 BANCOS ANGOLANOS<BR>COM DADOS PÚBLICOS E COMPANY PAGES NO LINKEDIN
##### LEVANTAMENTO REVISTA CARREIRA E ONKS GROWTH <BR>RESPONSÁVELTÉCNICO: DIEGO SEGURO | diego@onks.com.br<BR>https://revistacarreira.ao/ | https://www.onks.ao/

##### 0) IMPORTAÇÃO DE BIBLIOTECAS E BANCO DE DADOS
"""

# Importação da biblioteca Pandas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display, clear_output
import time

# Importação dos dados no Google Sheets
# Criação de variáveis de de Sheet ID e GID das abas
sheet_id = "1aQqJ7JRzE17E99kA2ACJ_Cnijt8TiLRNRPd97hcPhqQ"
sheet_gids = {
                "Permanencia": "1176165183",
                "Geodistribuição de Funcionários": "1227357502",
                "Funcionários por Setores": "505398827",
                "Principais Competências": "1889413329",
                "Variacoes de Quadro": "150748080"
             }
# Parametrização de URL para coleta de dados por dataframe
dfs = {
    name: pd.read_csv(
        f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&gid={gid}"
    )
    for name, gid in sheet_gids.items()
}

# Numeração dos dataframes
for i, (name, gid) in enumerate(sheet_gids.items(), start=1):
    url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&gid={gid}"
    globals()[f"df_{i}"] = pd.read_csv(url)

# Lista dos bancos sistêmicos
bancos_sistemicos = [
    'BAI',
    'BANCO DE FOMENTO ANGOLA',
    'BFA',
    'BANCO BIC ANGOLA',
    'BIC',
    'BANCO DE POUPANÇA E CRÉDITO',
    'BPC',
    'BANCO MILLENNIUM ATLÂNTICO',
    'MILLENNIUM ATLÂNTICO',
    'BANCO ECONÓMICO',
    'BANCO SOL',
    'SOL',
    'STANDARD BANK',
    'BANCO KEVE',
    'KEVE',
    'BANCO DE NEGÓCIOS INTERNACIONAL',
    'BNI',
    'BANCO DE COMÉRCIO E INDÚSTRIA',
    'BCI'
]

def class_bank_sis (Banco):
    if Banco in bancos_sistemicos:
        return 'sim'
    else:
        return 'não'
df_2['Sistêmico?'] = df_2['Banco'].apply(class_bank_sis)
df_3['Sistêmico?'] = df_3['Banco'].apply(class_bank_sis)
df_4['Sistêmico?'] = df_4['Banco'].apply(class_bank_sis)
df_5['Sistêmico?'] = df_5['Banco'].apply(class_bank_sis)

"""##### 1) DATAFRAMES

###### 1.1) DF_1 - Funcionário / Permanência
"""

df_1.head()

df_1['Permanência Média (A,M)'] = df_1['Permanência Média (A,M)'].str.replace(',', '.').astype(float)

df_1["Meses (ROUND, Col. D)"].mean() / 12

"""###### 1.2) DF_2 - Geodistribuição de Funcionários"""

df_2.head()

"""###### 1.3) DF_3 - Funcionários por Setores"""

df_3.head()

"""###### 1.4) DF_4 - Principais Competências"""

df_4.head()

"""###### 1.5) DF_5 - Variações de Quadro"""

df_5.head()

"""##### 2) ANÁLISE INTRODUTÓRIA"""

# Quantidade somada de funcionários dos bancos analisados no df_1
df_1['Funcionarios'].sum()

# Quantidade somada de funcionários dos bancos analisados no df_2
df_2['Funcionarios'].sum()

# Média anual de permanência do setor
df_1['Anos  (ROUND, Col. E)'].mean()

# 10 Bancos com maior número de funcionários
df_1.groupby(by="Banco")['Funcionarios'].sum().sort_values(ascending=False).head(10).plot(
    kind='bar',
    figsize=(12, 6),
    color="#151127",
    title='1.1 - Top 10 Bancos por Número de Funcionários',
    rot=45)

df_1.groupby("Banco")['Meses (ROUND, Col. D)'].mean().sort_values(ascending=False)

# Média de permanência em meses por banco (ordenado)
df_1.groupby("Banco")['Meses (ROUND, Col. D)'].mean().sort_values(ascending=True).plot(
   kind='barh',
   figsize=(12, 10),
   color="#151127",
   title='1.2 - Média de Permanência em Meses por Banco'
)

# Média de permanência em meses por banco
df_1.groupby("Banco")['Meses (ROUND, Col. D)'].mean().plot(kind='barh',
                                                           figsize=(12, 10),
                                                           color="#151127",
                                                           title='1.2 - Média de Permanência em Meses por Banco')

# Departamento com maior número de funcionários
df_3.groupby(by="Setor")['Funcionários'].sum().sort_values(ascending=False).head(10).plot(
    kind='bar',
    figsize=(12, 6),
    color="#151127",
    title='1.3 - 10 Departamentos com Maior Número de Funcionários no Setor Bancário Angolano',
    rot=45)

# Criação de dataframes de Bancos Sistêmidos e Bancos Não Sistêmicos
df_1_sistemico = df_1[df_1['Sistêmico?'] == 'sim']
df_1_n_sistemico = df_1[df_1['Sistêmico?'] == 'não']

# Permanência em meses nos bancos sistêmicos
df_1_sistemico.groupby(by='Banco')['Meses (ROUNDUP, Col. D)'].mean().sort_values(ascending=False).head(10).plot(
    kind='bar',
    figsize=(12, 6),
    color="#151127",
    title='1.4 - Top 10 Bancos Sistêmicos com Maior Permanência Média (Meses)',
    rot=45)

# Permanência em meses nos bancos não sistêmicos
df_1_n_sistemico.groupby(by='Banco')['Meses (ROUNDUP, Col. D)'].mean().sort_values(ascending=False).head(10).plot(
    kind='bar',
    figsize=(12, 6),
    color="#151127",
    title='1.5 - Top 10 Bancos Não Sistêmicos com Maior Permanência Média (Meses)',
    rot=45)

# Criação do dataframe de país
df_2_pais = df_2[df_2['País'] == 'Country']

# Função de filtro de país
def pais_filter(pais):
    if pais == 'Angola':
        return "Angola"
    elif pais != 'Angola':
        return 'Outro País'
# Aplicação da função de filtro de país no dataframe de país
df_2_pais["onde?"] = df_2_pais['Cidade'].apply(pais_filter)

# Porcentagem de funcionários em Angola ou em outros países
df_2_pais.groupby(by="onde?")['Funcionarios'].sum().sort_values(ascending=False).plot.pie(
    subplots=True,
    figsize=(8, 8),
    colors=("#2F2B4C", "#403C68"),
    title='1.6 - Distribuição de Funcionários por País',
    autopct='%1.1f%%')

# Criação do dataframe de cidade
df_2_cidade = df_2[df_2['País'] == 'Angola']

# Função de filtro de cidade
def cidade_filter(cidade):
    if cidade == 'Luanda':
        return "Luanda"
    elif cidade != 'Luanda':
        return 'Outras regiões'
# Aplicação do filtro de cidade no dataframe de cidade
df_2_cidade["Qual Região?"] = df_2_cidade['Cidade'].apply(cidade_filter)

# Porcentagem de funcionários em Luanda ou em outras regiões
df_2_cidade.groupby(by='Qual Região?')['Funcionarios'].sum().plot.pie(
    subplots=True,
    figsize=(8, 8),
    colors=("#2F2B4C", "#403C68"),
    title='1.7 - Distribuição de Funcionários por Região',
    autopct='%1.1f%%')

# Criação de datafraes de Bancos Sistêmicos e Bancos Não Sistêmicos
df_4_sistemico = df_4[df_4['Sistêmico?'] == 'sim']
df_4_n_sistemico = df_4[df_4['Sistêmico?'] == 'não']

# 10 Competências com maior número de ocorrências nos bancos sistêmicos
df_4_sistemico.groupby(by="Competência")['Ocorrência'].sum().sort_values(ascending=False).head(10).plot(
    kind='bar',
    figsize=(12, 6),
    color="#151127",
    title='1.8 - Top 10 Competências mais Demandadas nos Bancos Sistêmicos',
    rot=45)

# 10 Competências com maior número de ocorrências nos bancos não sistêmicos
df_4_n_sistemico.groupby(by="Competência")['Ocorrência'].sum().sort_values(ascending=False).head(10).plot(
    kind='bar',
    figsize=(12, 6),
    color="#151127",
    title='1.9 - Top 10 Competências mais Demandadas nos Bancos Não Sistêmicos',
    rot=45)

# Criação do dataframe de variação positiva, ou seja: os departamentos que apresentação crescimento no quadro de funcionários
df_5_positiva_6m = df_5[df_5['Variação 6M Rótulo'] == 'aumento']

# Departamentos que mais contrataram nos últimos 6 meses
df_5_positiva_6m.groupby(by="Setor")['Variação 6M %'].sum().sort_values(ascending=False).head(10).plot(
    kind='bar',
    figsize=(12, 6),
    color="#151127",
    title='1.10 - Departamentos que mais Contrataram nos Últimos 6 Meses',
    rot=45)

# Criação do dataframe de variação positiva dos bancos sistêmicos
df_5_positiva_6m_sistemico = df_5_positiva_6m[df_5_positiva_6m['Sistêmico?'] == 'sim']

# Departamentos que mais contrataram nos últimos 6 meses nos bancos sistêmicos
df_5_positiva_6m_sistemico.groupby(by="Setor")['Variação 6M %'].mean().sort_values(ascending=False).head(6).plot(
    kind='bar',
    figsize=(12, 6),
    color="#151127",
    title='1.11 - Setores que mais Cresceram nos Últimos 6 Meses nos Bancos Sistêmicos',
    rot=45)

df_5_positiva_6m.groupby(by="Banco")['Variação 6M %'].median().sort_values(ascending=False).head(5)

# Bancos que mais contrataram nos últimos 6 meses nos bancos sistêmicos
df_5_positiva_6m.groupby(by="Banco")['Variação 6M %'].median().sort_values(ascending=False).head(5).plot(
    kind='bar',
    figsize=(12, 6),
    color="#151127",
    title='1.12 - Bancos que Mais Contrataram nos Últimos 6 Meses',
    rot=45)

"""##### 3) ANÁLISE POR DEPARTAMENTO"""

df_3_fin = df_3[df_3['Setor'] == "Financeiro"]
df_3_ven = df_3[df_3['Setor'] == "Vendas"]
df_3_eng = df_3[df_3['Setor'] == "Engenharia"]
df_3_tec = df_3[df_3['Setor'] == "Tecnologia da informação"]
df_3_sup = df_3[df_3['Setor'] == "Suporte"]
df_3_adm = df_3[df_3['Setor'] == "Administração"]
df_3_ops = df_3[df_3['Setor'] == "Operações"]
df_3_dvn = df_3[df_3['Setor'] == "Desenvolvimento de negócios"]
df_3_con = df_3[df_3['Setor'] == "Contabilidade"]
df_3_edu = df_3[df_3['Setor'] == "Educação"]

df_3_tec

df_3.groupby(by='Banco')['Funcionários'].sum()

(418*100)/2075

df_3_tec['Setor'].value_counts()

df_3_tec.head()

df_3_tec['Funcionários'].sum()

(410*100) / 1190

df_3_tec.groupby(by='Banco')['Funcionários'].sum().sort_values(ascending=False).head(4)

# 10 maiores departamentos financeiros
df_3_fin.groupby(by='Banco')['Funcionários'].sum().sort_values(ascending=False).head(10).plot(
    kind='bar',
    figsize=(12, 6),
    color="#151127",
    title='2.1 - Top 10 maiores departamentos financeiros',
    rot=45)

# 10 maiores departamentos comerciais
df_3_ven.groupby(by='Banco')['Funcionários'].sum().sort_values(ascending=False).head(10).plot(
    kind='bar',
    figsize=(12, 6),
    color="#151127",
    title='2.2 - Top 10 maiores departamentos comerciais',
    rot=45)

# 10 maiores departamentos de engenharia
df_3_eng.groupby(by='Banco')['Funcionários'].sum().sort_values(ascending=False).head(10).plot(
    kind='bar',
    figsize=(12, 6),
    color="#151127",
    title='2.3 - Top 10 maiores departamentos de engenharia',
    rot=45)

# 10 maiores departamentos de tecnologia da informação
df_3_tec.groupby(by='Banco')['Funcionários'].sum().sort_values(ascending=False).head(10).plot(
    kind='bar',
    figsize=(12, 6),
    color="#151127",
    title='2.4 - Top 10 maiores departamentos de tecnologia da informação',
    rot=45)

# 10 maiores departamentos de suporte
df_3_sup.groupby(by='Banco')['Funcionários'].sum().sort_values(ascending=False).head(10).plot(
    kind='bar',
    figsize=(12, 6),
    color="#151127",
    title='2.5 - Top 10 maiores departamentos de suporte',
    rot=45)

# 10 maiores departamentos administrativos
df_3_adm.groupby(by='Banco')['Funcionários'].sum().sort_values(ascending=False).head(10).plot(
    kind='bar',
    figsize=(12, 6),
    color="#151127",
    title='2.6 - Top 10 maiores departamentos administrativos',
    rot=45)

# 10 maiores departamentos de operações
df_3_ops.groupby(by='Banco')['Funcionários'].sum().sort_values(ascending=False).head(10).plot(
    kind='bar',
    figsize=(12, 6),
    color="#151127",
    title='2.7 - Top 10 maiores departamentos de operações',
    rot=45)

# 10 maiores departamentos de desenvolvimento de negócios
df_3_dvn.groupby(by='Banco')['Funcionários'].sum().sort_values(ascending=False).head(10).plot(
    kind='bar',
    figsize=(12, 6),
    color="#151127",
    title='2.8 - Top 10 maiores departamentos de desenvolvimento de negócios',
    rot=45)

# 10 maiores departamentos de contabilidade
df_3_con.groupby(by='Banco')['Funcionários'].sum().sort_values(ascending=False).head(10).plot(
    kind='bar',
    figsize=(12, 6),
    color="#151127",
    title='2.9 - Top 10 maiores departamentos de contabilidade',
    rot=45)

df_3_edu.groupby(by='Banco')['Funcionários'].sum().sort_values(ascending=False).head(10)

# 10 maiores departamentos de educação
df_3_edu.groupby(by='Banco')['Funcionários'].sum().sort_values(ascending=False).head(10).plot(
    kind='bar',
    figsize=(12, 6),
    color="#151127",
    title='2.10 - Top 10 maiores departamentos de educação',
    rot=45)

"""##### 4) ANÁLISE POR BANCO"""

# Junção do dataframe df_3 com o df_5 com left join, para preservação do total de funcionários
df_completo = pd.merge(df_3, df_5, on=['Banco', 'Setor'], how='left')

# Tratando dados ausentes - preenche NaN com 0% e "sem alteração"
df_completo['Variação 6M %'] = df_completo['Variação 6M %'].fillna(0).astype(float)
df_completo['Variação 6M Rótulo'] = df_completo['Variação 6M Rótulo'].fillna('sem alteração')

# Aplica sinal correto baseado no rótulo (+ para aumento, - para redução)
df_completo['Variação_6M_Com_Sinal'] = df_completo['Variação 6M %'].copy()
df_completo.loc[df_completo['Variação 6M Rótulo'] == 'redução', 'Variação_6M_Com_Sinal'] *= -1
df_completo.loc[df_completo['Variação 6M Rótulo'] == 'sem alteração', 'Variação_6M_Com_Sinal'] = 0

# CORREÇÃO: Calcula funcionários ANTES do crescimento
# Se Funcionários_Atual = Funcionários_Inicial × (1 + variação/100)
# Então Funcionários_Inicial = Funcionários_Atual / (1 + variação/100)
df_completo['Funcionários_Inicial'] = (
    df_completo['Funcionários'] / (1 + df_completo['Variação_6M_Com_Sinal'] / 100)
).round().astype(int)

# Calcula o crescimento real em números absolutos
df_completo['Crescimento_Real_Individual_6M'] = (
    df_completo['Funcionários'] - df_completo['Funcionários_Inicial']
)

# Agrega dados por setor: soma funcionários iniciais, atuais e crescimento
crescimento_por_setor = df_completo.groupby('Setor').agg({
    'Funcionários_Inicial': 'sum',  # Total funcionários inicial por setor
    'Funcionários': 'sum',  # Total funcionários atual por setor
    'Crescimento_Real_Individual_6M': 'sum',  # Crescimento total por setor
    'Banco': 'count'  # Quantos bancos operam no setor
}).rename(columns={'Banco': 'Num_Bancos'})

# Renomeia coluna para clareza
crescimento_por_setor = crescimento_por_setor.rename(columns={
    'Crescimento_Real_Individual_6M': 'Crescimento_Real_Setor_6M'
})

# Calcula variação percentual real por setor
crescimento_por_setor['Variação_Percentual_Setor_6M'] = (
    (crescimento_por_setor['Crescimento_Real_Setor_6M'] /
     crescimento_por_setor['Funcionários_Inicial']) * 100
).round(2)

# Adiciona dados do setor de volta ao dataframe principal
df_completo = df_completo.merge(
    crescimento_por_setor[['Crescimento_Real_Setor_6M', 'Variação_Percentual_Setor_6M']].reset_index(),
    on='Setor',
    how='left'
)

# Criação do dataframe de variação positiva
df_completo_var_p = df_completo[df_completo['Variação 6M Rótulo']	== 'aumento']
# Criação do dataframe de variação negativa
df_completo_var_n = df_completo[df_completo['Variação 6M Rótulo']	== 'redução']
# Criação do dataframe sem alteração ou variação
df_completo_s_alt = df_completo[df_completo['Variação 6M Rótulo']	== 'sem alteração']

"""###### 4.1) ANÁLISE DO CRESCIMENTO DO QUADRO POR BANCO"""

# Criação de dataframes de variação positiva por banco
plus_BAI = df_completo_var_p[df_completo_var_p['Banco']=='BAI']
plus_Standard = df_completo_var_p[df_completo_var_p['Banco']=='Standard Bank Angola']
plus_BCA = df_completo_var_p[df_completo_var_p['Banco']=='BCA - Banco Comercial Angolano']
plus_BFA = df_completo_var_p[df_completo_var_p['Banco']=='BFA - Banco de Fomento Angola']
plus_BIC = df_completo_var_p[df_completo_var_p['Banco']=='Banco BIC Angola']
plus_Caixa = df_completo_var_p[df_completo_var_p['Banco']=='Banco Caixa Geral Angola']
plus_BCH = df_completo_var_p[df_completo_var_p['Banco']=='BCH - Banco Comercial do Huambo']
plus_BCI = df_completo_var_p[df_completo_var_p['Banco']=='BCI Angola']
plus_BDA = df_completo_var_p[df_completo_var_p['Banco']=='BDA - Banco de Desenvolvimento de Angola']
plus_Económico = df_completo_var_p[df_completo_var_p['Banco']=='Banco Económico']
plus_BNI = df_completo_var_p[df_completo_var_p['Banco']=='Banco BNI']
plus_BPC = df_completo_var_p[df_completo_var_p['Banco']=='BPC - Banco de Poupança e Crédito']
plus_MILLENNIUM = df_completo_var_p[df_completo_var_p['Banco']=='BANCO MILLENNIUM ATLANTICO']
plus_Keve = df_completo_var_p[df_completo_var_p['Banco']=='Banco Keve']
plus_Prestígio = df_completo_var_p[df_completo_var_p['Banco']=='Banco Prestígio']
plus_SOL = df_completo_var_p[df_completo_var_p['Banco']=='Banco SOL']
plus_Valor = df_completo_var_p[df_completo_var_p['Banco']=='Banco Valor S.A.']
plus_VTB = df_completo_var_p[df_completo_var_p['Banco']=='Banco VTB África S.A.']
plus_Access = df_completo_var_p[df_completo_var_p['Banco']=='Access Bank Angola']
plus_Yetu = df_completo_var_p[df_completo_var_p['Banco']=='Banco Yetu S,A']
plus_BCS = df_completo_var_p[df_completo_var_p['Banco']=='Banco BCS']
plus_Finibanco = df_completo_var_p[df_completo_var_p['Banco']=='Finibanco']

# Agrega por setor e soma o crescimento real para o BAI bank e para o setor geral
crescimento_bai_setor = plus_BAI.groupby('Setor').agg({
    'Crescimento_Real_Individual_6M': 'sum',
    'Crescimento_Real_Setor_6M': 'mean' # Usando a média para o crescimento do setor, já que o valor é o mesmo para o setor
}).sort_values(by='Crescimento_Real_Individual_6M', ascending=False)

# Seleciona os top 5 setores com maior crescimento no BAI bank
top_5_setores_bai = crescimento_bai_setor.head(5)

# Cria o gráfico de barras empilhadas
plt.figure(figsize=(12, 6))
top_5_setores_bai.plot(kind='bar', stacked=True, color=['#000000', '#362E5F'], ax=plt.gca()) # Use ax=plt.gca() to plot on the current axes and stacked=True
plt.title('Crescimento de Departamentos no Banco BAI vs. Crescimento do Setor (Últimos 6 Meses)')
plt.xlabel('Setor', fontsize=12)
plt.ylabel('Crescimento Real de Funcionários (6M)', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.legend(['Crescimento no Banco BAI', 'Crescimento Médio do Setor']) # Atualiza a legenda
plt.tight_layout()
plt.show()

# Função para criação do gráfico de crescimento comparado de cada banco com cresciemendo do setor
def gerar_grafico_crescimento_banco(df_banco, nome_banco, top_n=5, figsize=(12, 6), salvar=False):
    """
    Gera um gráfico de barras empilhadas comparando o crescimento individual do banco
    com o crescimento médio do setor por departamento.

    Parâmetros:
    - df_banco: DataFrame filtrado para um banco específico
    - nome_banco: String com o nome do banco para o título
    - top_n: Número de setores top a serem exibidos (padrão: 5)
    - figsize: Tupla com o tamanho da figura (padrão: (12, 6))
    - salvar: Se True, salva o gráfico como arquivo (padrão: False)
    """
    # Agrega por setor e soma o crescimento real para o banco e para o setor geral
    crescimento_banco_setor = df_banco.groupby('Setor').agg({
        'Crescimento_Real_Individual_6M': 'sum',
        'Crescimento_Real_Setor_6M': 'sum'  # Usando a média para o crescimento do setor
    }).sort_values(by='Crescimento_Real_Individual_6M', ascending=False)

    # Seleciona os top N setores com maior crescimento no banco
    top_setores_banco = crescimento_banco_setor.head(top_n)

    # Cria o gráfico de barras empilhadas
    fig, ax = plt.subplots(figsize=figsize)
    top_setores_banco.plot(kind='bar', stacked=True, color=['#000000', '#362E5F'], ax=ax)
    ax.set_title(f'Crescimento de Departamentos no {nome_banco} vs. Crescimento do Setor (Últimos 6 Meses)')
    ax.set_xlabel('Setor', fontsize=12)
    ax.set_ylabel('Crescimento Real de Funcionários (6M)', fontsize=12)
    plt.setp(ax.get_xticklabels(), rotation=45, ha='right')
    ax.legend([f'Crescimento no {nome_banco}', 'Crescimento do Setor'])

    plt.tight_layout()

    if salvar:
        # Remove caracteres especiais do nome para o arquivo
        nome_arquivo = nome_banco.replace(' ', '_').replace('-', '').replace('.', '').replace(',', '')
        plt.savefig(f'crescimento_{nome_arquivo}.png', dpi=300, bbox_inches='tight')

    plt.show()
    plt.close()  # Importante no Colab para liberar memória

    return fig, ax

# Dicionário com todos os DataFrames e nomes dos bancos
bancos_data = {
    'BAI': plus_BAI,
    'Standard Bank Angola': plus_Standard,
    'BCA - Banco Comercial Angolano': plus_BCA,
    'BFA - Banco de Fomento Angola': plus_BFA,
    'Banco BIC Angola': plus_BIC,
    'Banco Caixa Geral Angola': plus_Caixa,
    'BCH - Banco Comercial do Huambo': plus_BCH,
    'BCI Angola': plus_BCI,
    'BDA - Banco de Desenvolvimento de Angola': plus_BDA,
    'Banco Económico': plus_Económico,
    'Banco BNI': plus_BNI,
    'BPC - Banco de Poupança e Crédito': plus_BPC,
    'BANCO MILLENNIUM ATLANTICO': plus_MILLENNIUM,
    'Banco Keve': plus_Keve,
    'Banco Prestígio': plus_Prestígio,
    'Banco SOL': plus_SOL,
    'Banco Valor S.A.': plus_Valor,
    'Banco VTB África S.A.': plus_VTB,
    'Access Bank Angola': plus_Access,
    'Banco Yetu S,A': plus_Yetu,
    'Banco BCS': plus_BCS,
    'Finibanco': plus_Finibanco
}

gerar_grafico_crescimento_banco(plus_BAI, 'BAI')

#Tabela Comparativa (Crescimento BAI em vagas X Crescimento MERCADO em vaga)
plus_BAI.groupby('Setor').agg({
    'Crescimento_Real_Individual_6M': 'sum',
    'Crescimento_Real_Setor_6M': 'mean' # Usando a média para o crescimento do setor, já que o valor é o mesmo para o setor
}).sort_values(by='Crescimento_Real_Individual_6M', ascending=False).head(5)

gerar_grafico_crescimento_banco(plus_Standard, 'Standard Bank Angola')

#Tabela Comparativa (Crescimento Standart em vagas X Crescimento MERCADO em vaga)
plus_Standard.groupby('Setor').agg({
    'Crescimento_Real_Individual_6M': 'sum',
    'Crescimento_Real_Setor_6M': 'mean' # Usando a média para o crescimento do setor, já que o valor é o mesmo para o setor
}).sort_values(by='Crescimento_Real_Individual_6M', ascending=False)

gerar_grafico_crescimento_banco(plus_BCA, 'BCA - Banco Comercial Angolano')

#Tabela Comparativa (Crescimento BCA em vagas X Crescimento MERCADO em vaga)
plus_BCA.groupby('Setor').agg({
    'Crescimento_Real_Individual_6M': 'sum',
    'Crescimento_Real_Setor_6M': 'mean' # Usando a média para o crescimento do setor, já que o valor é o mesmo para o setor
}).sort_values(by='Crescimento_Real_Individual_6M', ascending=False)

gerar_grafico_crescimento_banco(plus_BFA, 'BFA - Banco de Fomento Angola')

#Tabela Comparativa (Crescimento BFA em vagas X Crescimento MERCADO em vaga)
plus_BFA.groupby('Setor').agg({
    'Crescimento_Real_Individual_6M': 'sum',
    'Crescimento_Real_Setor_6M': 'mean' # Usando a média para o crescimento do setor, já que o valor é o mesmo para o setor
}).sort_values(by='Crescimento_Real_Individual_6M', ascending=False).head(5)

gerar_grafico_crescimento_banco(plus_BIC, 'Banco BIC Angola')

#Tabela Comparativa (Crescimento BIC em vagas X Crescimento MERCADO em vaga)
plus_BIC.groupby('Setor').agg({
    'Crescimento_Real_Individual_6M': 'sum',
    'Crescimento_Real_Setor_6M': 'mean' # Usando a média para o crescimento do setor, já que o valor é o mesmo para o setor
}).sort_values(by='Crescimento_Real_Individual_6M', ascending=False).head(5)

gerar_grafico_crescimento_banco(plus_Caixa, 'Banco Caixa Geral Angola')

#Tabela Comparativa (Crescimento Banco Caixa Geral Angola em vagas X Crescimento MERCADO em vaga)
plus_Caixa.groupby('Setor').agg({
    'Crescimento_Real_Individual_6M': 'sum',
    'Crescimento_Real_Setor_6M': 'mean' # Usando a média para o crescimento do setor, já que o valor é o mesmo para o setor
}).sort_values(by='Crescimento_Real_Individual_6M', ascending=False).head(5)

gerar_grafico_crescimento_banco(plus_BCH, 'BCH - Banco Comercial do Huambo')

#Tabela Comparativa (Crescimento BCH - Banco Comercial do Huambo em vagas X Crescimento MERCADO em vaga)
plus_BCH.groupby('Setor').agg({
    'Crescimento_Real_Individual_6M': 'sum',
    'Crescimento_Real_Setor_6M': 'mean' # Usando a média para o crescimento do setor, já que o valor é o mesmo para o setor
}).sort_values(by='Crescimento_Real_Individual_6M', ascending=False).head(5)

gerar_grafico_crescimento_banco(plus_BCI, 'BCI Angola')

#Tabela Comparativa (Crescimento BCI Angola em vagas X Crescimento MERCADO em vaga)
plus_BCI.groupby('Setor').agg({
    'Crescimento_Real_Individual_6M': 'sum',
    'Crescimento_Real_Setor_6M': 'mean' # Usando a média para o crescimento do setor, já que o valor é o mesmo para o setor
}).sort_values(by='Crescimento_Real_Individual_6M', ascending=False).head(5)

gerar_grafico_crescimento_banco(plus_BDA, 'BDA - Banco de Desenvolvimento de Angola')

#Tabela Comparativa (Crescimento BDA - Banco de Desenvolvimento de Angola em vagas X Crescimento MERCADO em vaga)
plus_BDA.groupby('Setor').agg({
    'Crescimento_Real_Individual_6M': 'sum',
    'Crescimento_Real_Setor_6M': 'mean' # Usando a média para o crescimento do setor, já que o valor é o mesmo para o setor
}).sort_values(by='Crescimento_Real_Individual_6M', ascending=False).head(5)

gerar_grafico_crescimento_banco(plus_Económico, 'Banco Económico')

#Tabela Comparativa (Crescimento Banco Económico em vagas X Crescimento MERCADO em vaga)
plus_Económico.groupby('Setor').agg({
    'Crescimento_Real_Individual_6M': 'sum',
    'Crescimento_Real_Setor_6M': 'mean' # Usando a média para o crescimento do setor, já que o valor é o mesmo para o setor
}).sort_values(by='Crescimento_Real_Individual_6M', ascending=False).head(5)

gerar_grafico_crescimento_banco(plus_BNI, 'Banco BNI')

#Tabela Comparativa (Crescimento Banco BNI em vagas X Crescimento MERCADO em vaga)
plus_BNI.groupby('Setor').agg({
    'Crescimento_Real_Individual_6M': 'sum',
    'Crescimento_Real_Setor_6M': 'mean' # Usando a média para o crescimento do setor, já que o valor é o mesmo para o setor
}).sort_values(by='Crescimento_Real_Individual_6M', ascending=False).head(5)

gerar_grafico_crescimento_banco(plus_BPC, 'BPC - Banco de Poupança e Crédito')

#Tabela Comparativa (Crescimento BPC - Banco de Poupança e Crédito em vagas X Crescimento MERCADO em vaga)
plus_BPC.groupby('Setor').agg({
    'Crescimento_Real_Individual_6M': 'sum',
    'Crescimento_Real_Setor_6M': 'mean' # Usando a média para o crescimento do setor, já que o valor é o mesmo para o setor
}).sort_values(by='Crescimento_Real_Individual_6M', ascending=False).head(5)

gerar_grafico_crescimento_banco(plus_MILLENNIUM, 'BANCO MILLENNIUM ATLANTICO')

#Tabela Comparativa (Crescimento BANCO MILLENNIUM ATLANTICO em vagas X Crescimento MERCADO em vaga)
plus_MILLENNIUM.groupby('Setor').agg({
    'Crescimento_Real_Individual_6M': 'sum',
    'Crescimento_Real_Setor_6M': 'mean' # Usando a média para o crescimento do setor, já que o valor é o mesmo para o setor
}).sort_values(by='Crescimento_Real_Individual_6M', ascending=False).head(5)

gerar_grafico_crescimento_banco(plus_Keve, 'Banco Keve')

#Tabela Comparativa (Crescimento Banco Keve em vagas X Crescimento MERCADO em vaga)
plus_Keve.groupby('Setor').agg({
    'Crescimento_Real_Individual_6M': 'sum',
    'Crescimento_Real_Setor_6M': 'mean' # Usando a média para o crescimento do setor, já que o valor é o mesmo para o setor
}).sort_values(by='Crescimento_Real_Individual_6M', ascending=False).head(5)

gerar_grafico_crescimento_banco(plus_SOL, 'Banco SOL')

#Tabela Comparativa (Crescimento Banco SOL X Crescimento MERCADO em vaga)
plus_SOL.groupby('Setor').agg({
    'Crescimento_Real_Individual_6M': 'sum',
    'Crescimento_Real_Setor_6M': 'mean' # Usando a média para o crescimento do setor, já que o valor é o mesmo para o setor
}).sort_values(by='Crescimento_Real_Individual_6M', ascending=False).head(5)

gerar_grafico_crescimento_banco(plus_Valor, 'Banco Valor S.A.')

#Tabela Comparativa (Crescimento Banco Valor S.A. X Crescimento MERCADO em vaga)
plus_Valor.groupby('Setor').agg({
    'Crescimento_Real_Individual_6M': 'sum',
    'Crescimento_Real_Setor_6M': 'mean' # Usando a média para o crescimento do setor, já que o valor é o mesmo para o setor
}).sort_values(by='Crescimento_Real_Individual_6M', ascending=False).head(5)

gerar_grafico_crescimento_banco(plus_VTB, 'Banco VTB África S.A.')

#Tabela Comparativa (Crescimento Banco VTB África S.A. X Crescimento MERCADO em vaga)
plus_VTB.groupby('Setor').agg({
    'Crescimento_Real_Individual_6M': 'sum',
    'Crescimento_Real_Setor_6M': 'mean' # Usando a média para o crescimento do setor, já que o valor é o mesmo para o setor
}).sort_values(by='Crescimento_Real_Individual_6M', ascending=False).head(5)

gerar_grafico_crescimento_banco(plus_Access, 'Access Bank Angola')

#Tabela Comparativa (Crescimento Access Bank Angola X Crescimento MERCADO em vaga)
plus_Access.groupby('Setor').agg({
    'Crescimento_Real_Individual_6M': 'sum',
    'Crescimento_Real_Setor_6M': 'mean' # Usando a média para o crescimento do setor, já que o valor é o mesmo para o setor
}).sort_values(by='Crescimento_Real_Individual_6M', ascending=False).head(5)

gerar_grafico_crescimento_banco(plus_Yetu, 'Banco Yetu S,A')

#Tabela Comparativa (Crescimento Banco Yetu S,A X Crescimento MERCADO em vaga)
plus_Yetu.groupby('Setor').agg({
    'Crescimento_Real_Individual_6M': 'sum',
    'Crescimento_Real_Setor_6M': 'mean' # Usando a média para o crescimento do setor, já que o valor é o mesmo para o setor
}).sort_values(by='Crescimento_Real_Individual_6M', ascending=False).head(5)

gerar_grafico_crescimento_banco(plus_BCS, 'Banco BCS')

#Tabela Comparativa (Crescimento Banco BCS X Crescimento MERCADO em vaga)
plus_BCS.groupby('Setor').agg({
    'Crescimento_Real_Individual_6M': 'sum',
    'Crescimento_Real_Setor_6M': 'mean' # Usando a média para o crescimento do setor, já que o valor é o mesmo para o setor
}).sort_values(by='Crescimento_Real_Individual_6M', ascending=False).head(5)

"""###### 4.2) ANÁLISE DA REDUÇÃO DE QUADRO POR BANCO"""

# Criação de dataframes de variação negativa por banco
loss_BAI = df_completo_var_n[df_completo_var_n['Banco']=='BAI']
loss_Standard = df_completo_var_n[df_completo_var_n['Banco']=='Standard Bank Angola']
loss_BCA = df_completo_var_n[df_completo_var_n['Banco']=='BCA - Banco Comercial Angolano']
loss_BFA = df_completo_var_n[df_completo_var_n['Banco']=='BFA - Banco de Fomento Angola']
loss_BIC = df_completo_var_n[df_completo_var_n['Banco']=='Banco BIC Angola']
loss_Caixa = df_completo_var_n[df_completo_var_n['Banco']=='Banco Caixa Geral Angola']
loss_BCH = df_completo_var_n[df_completo_var_n['Banco']=='BCH - Banco Comercial do Huambo']
loss_BCI = df_completo_var_n[df_completo_var_n['Banco']=='BCI Angola']
loss_BDA = df_completo_var_n[df_completo_var_n['Banco']=='BDA - Banco de Desenvolvimento de Angola']
loss_Económico = df_completo_var_n[df_completo_var_n['Banco']=='Banco Económico']
loss_BNI = df_completo_var_n[df_completo_var_n['Banco']=='Banco BNI']
loss_BPC = df_completo_var_n[df_completo_var_n['Banco']=='BPC - Banco de Poupança e Crédito']
loss_MILLENNIUM = df_completo_var_n[df_completo_var_n['Banco']=='BANCO MILLENNIUM ATLANTICO']
loss_Keve = df_completo_var_n[df_completo_var_n['Banco']=='Banco Keve']
loss_Prestígio = df_completo_var_n[df_completo_var_n['Banco']=='Banco Prestígio']
loss_SOL = df_completo_var_n[df_completo_var_n['Banco']=='Banco SOL']
loss_Valor = df_completo_var_n[df_completo_var_n['Banco']=='Banco Valor S.A.']
loss_VTB = df_completo_var_n[df_completo_var_n['Banco']=='Banco VTB África S.A.']
loss_Access = df_completo_var_n[df_completo_var_n['Banco']=='Access Bank Angola']
loss_Yetu = df_completo_var_n[df_completo_var_n['Banco']=='Banco Yetu S,A']
loss_BCS = df_completo_var_n[df_completo_var_n['Banco']=='Banco BCS']
loss_Finibanco = df_completo_var_n[df_completo_var_n['Banco']=='Finibanco']

plus_Finibanco.head()

loss_Finibanco.head()

import matplotlib.pyplot as plt
from IPython.display import display, clear_output
import time

def gerar_grafico_reducao_banco(df_banco, nome_banco, top_n=5, figsize=(12, 6), salvar=False):
    """
    Gera um gráfico de barras empilhadas comparando a redução individual do banco
    com a redução média do setor por departamento.

    Parâmetros:
    - df_banco: DataFrame filtrado para um banco específico
    - nome_banco: String com o nome do banco para o título
    - top_n: Número de setores top a serem exibidos (padrão: 5)
    - figsize: Tupla com o tamanho da figura (padrão: (12, 6))
    - salvar: Se True, salva o gráfico como arquivo (padrão: False)
    """
    # Agrega por setor e soma a redução real para o banco e para o setor geral
    reducao_banco_setor = df_banco.groupby('Setor').agg({
        'Crescimento_Real_Individual_6M': 'sum',  # Na verdade é redução (valores negativos)
        'Crescimento_Real_Setor_6M': 'sum'  # Usando a média para a redução do setor
    }).sort_values(by='Crescimento_Real_Individual_6M', ascending=True)  # Ascending=True para maiores reduções primeiro

    # Seleciona os top N setores com maior redução no banco
    top_setores_banco = reducao_banco_setor.head(top_n)

    # Converte para valores absolutos para melhor visualização
    top_setores_banco_abs = top_setores_banco.abs()

    # Cria o gráfico de barras empilhadas
    fig, ax = plt.subplots(figsize=figsize)
    top_setores_banco_abs.plot(kind='bar', stacked=True, color=['#000000', '#362E5F'], ax=ax)
    ax.set_title(f'Redução de Departamentos no {nome_banco} vs. Redução do Setor (Últimos 6 Meses)')
    ax.set_xlabel('Setor', fontsize=12)
    ax.set_ylabel('Redução de Funcionários (6M) - Valores Absolutos', fontsize=12)
    plt.setp(ax.get_xticklabels(), rotation=45, ha='right')
    ax.legend([f'Redução no {nome_banco}', 'Redução Total do Setor'])

    plt.tight_layout()

    if salvar:
        # Remove caracteres especiais do nome para o arquivo
        nome_arquivo = nome_banco.replace(' ', '_').replace('-', '').replace('.', '').replace(',', '')
        plt.savefig(f'reducao_{nome_arquivo}.png', dpi=300, bbox_inches='tight')

    plt.show()
    plt.close()  # Importante no Colab para liberar memória

    return fig, ax

# Dicionário apenas com os bancos que tiveram reduções
bancos_reducao_data = {
    'BCA - Banco Comercial Angolano': loss_BCA,
    'BFA - Banco de Fomento Angola': loss_BFA,
    'Banco BIC Angola': loss_BIC,
    'Banco Caixa Geral Angola': loss_Caixa,
    'BCI Angola': loss_BCI,
    'BDA - Banco de Desenvolvimento de Angola': loss_BDA,
    'Banco Económico': loss_Económico,
    'Banco BNI': loss_BNI,
    'Banco SOL': loss_SOL,
    'Banco Valor S.A.': loss_Valor,
    'Banco VTB África S.A.': loss_VTB,
    'Access Bank Angola': loss_Access,
    'Banco Yetu S,A': loss_Yetu,
    'Banco BCS': loss_BCS
}

gerar_grafico_reducao_banco(loss_BCA, 'BCA - Banco Comercial Angolano')

gerar_grafico_reducao_banco(loss_BFA, 'BFA - Banco de Fomento Angola')

gerar_grafico_reducao_banco(loss_BIC, 'Banco BIC Angola')

gerar_grafico_reducao_banco(loss_Caixa, 'Banco Caixa Geral Angola')

gerar_grafico_reducao_banco(loss_BCI, 'BCI Angola')

gerar_grafico_reducao_banco(loss_BDA, 'BDA - Banco de Desenvolvimento de Angola')

gerar_grafico_reducao_banco(loss_Económico, 'Banco Económico')

gerar_grafico_reducao_banco(loss_BNI, 'Banco BNI')

gerar_grafico_reducao_banco(loss_SOL, 'Banco SOL')

gerar_grafico_reducao_banco(loss_Valor, 'Banco Valor S.A.')

gerar_grafico_reducao_banco(loss_VTB, 'Banco VTB África S.A.')

gerar_grafico_reducao_banco(loss_Access, 'Access Bank Angola')

gerar_grafico_reducao_banco(loss_Yetu, 'Banco Yetu S,A')

gerar_grafico_reducao_banco(loss_BCS, 'Banco BCS')

# @title Variação 6M Rótulo vs Funcionários

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(df_completo['Variação 6M Rótulo'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(df_completo, x='Funcionários', y='Variação 6M Rótulo', inner='stick', palette='Dark2')
plt.title('Dinâmica do Quadro de Funcionários nos Bancos Angolanos Analisados', fontsize=14, weight='bold')
sns.despine(top=True, right=True, bottom=True, left=True)

"""# Matéria Portal da TI"""

df_completo_var_p['Crescimento_Real_Setor_6M'].sum()

df_3.head(3)

df_3['Funcionários'].sum()

df_5_aumento = df_5[df_5['Variação 6M Rótulo']=='aumento']

df_5_aumento['Variação 6M %'].sum()

df_3['Funcionários'].sum()

df_completo_var_p['Funcionários'].sum()

df_completo_var_p['Variação 6M %'].sum()

df_5.head(3)

df_3['Funcionários'].sum()

df_3.groupby(by='Setor')['Funcionários'].sum().sort_values(ascending=False)

df_completo_var_p.groupby(by='Setor')['Crescimento_Real_Setor_6M'].sum().sort_values(ascending=False)

import matplotlib.pyplot as plt

# Criar o gráfico com cor azul escuro e rótulos inclinados
ax = df_3_tec.groupby(by='Banco')['Funcionários'].sum().sort_values(ascending=False).head(4).plot.bar(
    color='darkblue',  # Cor azul escuro
    figsize=(10, 6)    # Tamanho do gráfico (opcional)
)

# Inclinar os rótulos do eixo x
plt.xticks(rotation=45, ha='right')

# Adicionar título e labels (opcional)
plt.title('Top 4 Bancos por Número de Funcionários de TI')
plt.xlabel('Banco')
plt.ylabel('Número de Funcionários')

# Ajustar layout para evitar corte dos rótulos
plt.tight_layout()

# Exibir o gráfico
plt.show()

df_3_tec.head()

df_completo_var_p_ti = df_completo_var_p[df_completo_var_p['Setor'] == 'Tecnologia da informação']
df_completo_var_n_ti = df_completo_var_n[df_completo_var_n['Setor'] == 'Tecnologia da informação']

contratacoes_ti = df_completo_var_p_ti['Crescimento_Real_Setor_6M'].sum()
demissoes_ti = df_completo_var_n_ti['Crescimento_Real_Setor_6M'].sum()
crescimento_real = contratacoes_ti - demissoes_ti

contratacoes_ti

demissoes_ti

crescimento_real

import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from matplotlib.patches import FancyBboxPatch
import plotly.graph_objects as go
import plotly.express as px

# Seus dados
contratacoes_ti = df_completo_var_p_ti['Crescimento_Real_Setor_6M'].sum()
demissoes_ti = df_completo_var_n_ti['Crescimento_Real_Setor_6M'].sum()
crescimento_real = contratacoes_ti - demissoes_ti

# VISUALIZAÇÃO 1: Gráfico de Cascata (Waterfall Chart)
fig, ax = plt.subplots(figsize=(12, 8))

# Dados para o gráfico de cascata
categorias = ['Contratações', 'Demissões', 'Crescimento\nLíquido']
valores = [contratacoes_ti, -abs(demissoes_ti), crescimento_real]
cores = ['#2E8B57', '#DC143C', '#1E90FF']

# Posições das barras
x_pos = np.arange(len(categorias))
cumulative = [0, contratacoes_ti, contratacoes_ti - abs(demissoes_ti)]

# Criar barras
bars = ax.bar(x_pos[:2], [contratacoes_ti, abs(demissoes_ti)],
              bottom=[0, contratacoes_ti - abs(demissoes_ti)],
              color=cores[:2], alpha=0.8, width=0.6)

# Barra do crescimento líquido
ax.bar(x_pos[2], crescimento_real, color=cores[2], alpha=0.8, width=0.6)

# Conectores (linhas pontilhadas)
ax.plot([0.3, 0.7], [contratacoes_ti, contratacoes_ti], 'k--', alpha=0.5)
ax.plot([1.3, 1.7], [crescimento_real, crescimento_real], 'k--', alpha=0.5)

# Personalização
ax.set_xticks(x_pos)
ax.set_xticklabels(categorias, fontsize=12, fontweight='bold')
ax.set_ylabel('Número de Funcionários', fontsize=12, fontweight='bold')
ax.set_title('Análise de Crescimento de TI no Setor Bancário\n(Últimos 6 Meses)',
             fontsize=16, fontweight='bold', pad=20)

# Adicionar valores nas barras
for i, v in enumerate([contratacoes_ti, abs(demissoes_ti), crescimento_real]):
    if i == 2:
        ax.text(i, v/2, f'+{int(v)}', ha='center', va='center',
                fontweight='bold', fontsize=14, color='white')
    else:
        height = contratacoes_ti if i == 0 else contratacoes_ti - abs(demissoes_ti)/2
        ax.text(i, height/2 if i == 0 else height,
                f'+{int(v)}' if i == 0 else f'-{int(v)}',
                ha='center', va='center', fontweight='bold',
                fontsize=14, color='white')

# Grid e styling
ax.grid(axis='y', alpha=0.3, linestyle='-', linewidth=0.5)
ax.set_facecolor('#f8f9fa')
plt.tight_layout()
plt.show()

# VISUALIZAÇÃO 2: Gráfico de Gauge/Velocímetro com Plotly
fig_gauge = go.Figure(go.Indicator(
    mode = "gauge+number+delta",
    value = crescimento_real,
    domain = {'x': [0, 1], 'y': [0, 1]},
    title = {'text': "Crescimento Líquido de TI<br><span style='font-size:0.8em;color:gray'>Últimos 6 Meses</span>"},
    delta = {'reference': 0, 'position': "top"},
    gauge = {
        'axis': {'range': [None, contratacoes_ti * 1.2]},
        'bar': {'color': "#1E90FF"},
        'steps': [
            {'range': [0, contratacoes_ti * 0.3], 'color': "#FFE6E6"},
            {'range': [contratacoes_ti * 0.3, contratacoes_ti * 0.7], 'color': "#FFFFCC"},
            {'range': [contratacoes_ti * 0.7, contratacoes_ti * 1.2], 'color': "#E6FFE6"}
        ],
        'threshold': {
            'line': {'color': "red", 'width': 4},
            'thickness': 0.75,
            'value': contratacoes_ti * 0.5
        }
    }
))

fig_gauge.update_layout(
    paper_bgcolor = "white",
    font = {'color': "darkblue", 'family': "Arial"},
    width=500, height=400
)

fig_gauge.show()

# VISUALIZAÇÃO 3: Gráfico de Barras Moderno com Anotações
fig, ax = plt.subplots(figsize=(10, 6))

# Dados
categorias = ['Contratações', 'Demissões', 'Crescimento Líquido']
valores = [contratacoes_ti, abs(demissoes_ti), crescimento_real]
cores = ['#00C851', '#FF4444', '#2BBBAD']

# Criar barras
bars = ax.bar(categorias, valores, color=cores, alpha=0.8,
              edgecolor='white', linewidth=2)

# Adicionar valores nas barras
for i, (bar, valor) in enumerate(zip(bars, valores)):
    height = bar.get_height()
    ax.text(bar.get_x() + bar.get_width()/2., height + 5,
            f'{int(valor):+d}' if i == 2 else f'{int(valor):,}',
            ha='center', va='bottom', fontweight='bold', fontsize=12)

# Personalização
ax.set_ylabel('Número de Funcionários', fontweight='bold', fontsize=12)
ax.set_title('Dinâmica de Crescimento de TI no Setor Bancário Angolano\n(Últimos 6 Meses)',
             fontweight='bold', fontsize=14, pad=20)

# Adicionar linha de referência para zero
ax.axhline(y=0, color='black', linestyle='-', alpha=0.3)

# Styling
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.grid(axis='y', alpha=0.3)
ax.set_facecolor('#f8f9fa')

plt.xticks(rotation=0, fontweight='bold')
plt.tight_layout()
plt.show()

# VISUALIZAÇÃO 4: Gráfico de Fluxo/Sankey Simulado
fig, ax = plt.subplots(figsize=(12, 6))

# Posições
left_pos = 0.2
right_pos = 0.8
center_pos = 0.5

# Criar retângulos representando os fluxos
# Contratações
rect_contratos = FancyBboxPatch((left_pos-0.05, 0.3), 0.1, 0.4,
                                boxstyle="round,pad=0.01",
                                facecolor='#00C851', alpha=0.7)
ax.add_patch(rect_contratos)

# Demissões
rect_demissoes = FancyBboxPatch((left_pos-0.05, -0.1), 0.1, 0.3,
                                boxstyle="round,pad=0.01",
                                facecolor='#FF4444', alpha=0.7)
ax.add_patch(rect_demissoes)

# Resultado
rect_resultado = FancyBboxPatch((right_pos-0.05, 0.1), 0.1, crescimento_real/contratacoes_ti*0.6,
                                boxstyle="round,pad=0.01",
                                facecolor='#2BBBAD', alpha=0.7)
ax.add_patch(rect_resultado)

# Setas
ax.annotate('', xy=(center_pos-0.1, 0.5), xytext=(left_pos+0.1, 0.5),
            arrowprops=dict(arrowstyle='->', lw=3, color='#00C851'))
ax.annotate('', xy=(center_pos-0.1, 0.05), xytext=(left_pos+0.1, 0.05),
            arrowprops=dict(arrowstyle='->', lw=3, color='#FF4444'))
ax.annotate('', xy=(right_pos-0.1, 0.3), xytext=(center_pos+0.1, 0.3),
            arrowprops=dict(arrowstyle='->', lw=4, color='#2BBBAD'))

# Textos
ax.text(left_pos, 0.5, f'Contratações\n+{int(contratacoes_ti)}',
        ha='center', va='center', fontweight='bold', fontsize=12)
ax.text(left_pos, 0.05, f'Demissões\n-{int(abs(demissoes_ti))}',
        ha='center', va='center', fontweight='bold', fontsize=12)
ax.text(right_pos, 0.3, f'Crescimento\nLíquido\n+{int(crescimento_real)}',
        ha='center', va='center', fontweight='bold', fontsize=12)

ax.set_xlim(0, 1)
ax.set_ylim(-0.2, 0.8)
ax.set_title('Fluxo de Crescimento de Profissionais de TI\n(Setor Bancário Angolano - Últimos 6 Meses)',
             fontweight='bold', fontsize=14, pad=20)
ax.axis('off')
plt.tight_layout()
plt.show()

# VISUALIZAÇÃO 5: Dashboard Resumido
fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2, figsize=(15, 10))
fig.suptitle('Dashboard: Crescimento de TI no Setor Bancário Angolano',
             fontsize=16, fontweight='bold')

# Gráfico 1: Barras principais
categorias = ['Contratações', 'Demissões', 'Crescimento']
valores = [contratacoes_ti, abs(demissoes_ti), crescimento_real]
cores = ['green', 'red', 'blue']
ax1.bar(categorias, valores, color=cores, alpha=0.7)
ax1.set_title('Números Absolutos', fontweight='bold')
for i, v in enumerate(valores):
    ax1.text(i, v + 10, str(int(v)), ha='center', fontweight='bold')

# Gráfico 2: Pizza da composição
ax2.pie([contratacoes_ti, abs(demissoes_ti)],
        labels=['Contratações', 'Demissões'],
        colors=['green', 'red'], autopct='%1.1f%%',
        startangle=90)
ax2.set_title('Composição do Movimento', fontweight='bold')

# Gráfico 3: Taxa de crescimento
taxa_crescimento = (crescimento_real / (contratacoes_ti - crescimento_real)) * 100
ax3.bar(['Taxa de Crescimento'], [taxa_crescimento], color='blue', alpha=0.7)
ax3.set_title('Taxa de Crescimento (%)', fontweight='bold')
ax3.text(0, taxa_crescimento + 1, f'{taxa_crescimento:.1f}%',
         ha='center', fontweight='bold')

# Gráfico 4: Métricas resumo
ax4.axis('off')
ax4.text(0.1, 0.8, f'Total de Contratações: {int(contratacoes_ti):,}',
         fontsize=12, fontweight='bold', transform=ax4.transAxes)
ax4.text(0.1, 0.6, f'Total de Demissões: {int(abs(demissoes_ti)):,}',
         fontsize=12, fontweight='bold', transform=ax4.transAxes)
ax4.text(0.1, 0.4, f'Crescimento Líquido: +{int(crescimento_real):,}',
         fontsize=12, fontweight='bold', color='blue', transform=ax4.transAxes)
ax4.text(0.1, 0.2, f'Taxa de Retenção: {((contratacoes_ti-abs(demissoes_ti))/contratacoes_ti*100):.1f}%',
         fontsize=12, fontweight='bold', transform=ax4.transAxes)
ax4.set_title('Resumo Executivo', fontweight='bold')

plt.tight_layout()
plt.show()

df_completo_var_n.groupby(by='Setor')['Crescimento_Real_Setor_6M'].sum().sort_values(ascending=False)

df_completo_var_n.head(1)

df_completo_var_n['Variação 6M Rótulo'].value_counts()

